model_name: facebook/wav2vec2-base-960h
language: en
dataset: librispeech_asr
train_split: train.clean.100
eval_split: validation.clean
test_split: test.clean
text_column: text
output_dir: outputs/wav2vec2_base_mtl
learning_rate: 3e-4
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
gradient_accumulation_steps: 1
num_train_epochs: 3
lambda_intensity: 1.0
warmup_steps: 500
fp16: true
ctc_zero_infinity: true
pad_to_multiple_of: 32000
